FROM pllee4/ubuntu-ci:20.04-C20

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Singapore

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENV USER=docker

RUN useradd -ms /bin/bash ${USER}

RUN mkdir -p /home/${USER}/ws

RUN mkdir -p /home/${USER}/ws/build

WORKDIR /home/${USER}/ws

COPY . /home/${USER}/ws/

ENTRYPOINT [ "/bin/bash"]
